FROM golang:latest

RUN apt-get update 

RUN groupadd -r mysql && useradd -r -g mysql mysql
RUN apt-get install -y mariadb-server \
    && mkdir -p /var/lib/mysql /var/run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld \
    && chmod 777 /var/run/mysqld

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]