version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app

# version: '3'
# services:
#   app:
#     image: simplecyclestudio/eludico:backup
#     volumes:
#       - ./logs:/app/logs
#       - ./dumps:/app/dumps
#       - ./config:/app/config